# BookLoop
spring.application.name=bookloop-api

# Conexão com o MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/bookloop_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}

# Mostra as queries SQL no console
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
